// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN7UtCYEJFpON3emyrG_PYdS6D1R7-2IU',
    appId: '1:138769918502:web:93dae34548d93446fed4e7',
    messagingSenderId: '138769918502',
    projectId: 'zero-ads-gallery',
    authDomain: 'zero-ads-gallery.firebaseapp.com',
    storageBucket: 'zero-ads-gallery.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9t_j0SazJaRjNAKe2U1wXNh6cq9tMec',
    appId: '1:138769918502:android:df1da940a4ba8d1ffed4e7',
    messagingSenderId: '138769918502',
    projectId: 'zero-ads-gallery',
    storageBucket: 'zero-ads-gallery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpM7sD1W3_PX_7oumRjGyN469_g2EdwnQ',
    appId: '1:138769918502:ios:f3edf3147deae369fed4e7',
    messagingSenderId: '138769918502',
    projectId: 'zero-ads-gallery',
    storageBucket: 'zero-ads-gallery.firebasestorage.app',
    iosBundleId: 'com.example.galleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpM7sD1W3_PX_7oumRjGyN469_g2EdwnQ',
    appId: '1:138769918502:ios:f3edf3147deae369fed4e7',
    messagingSenderId: '138769918502',
    projectId: 'zero-ads-gallery',
    storageBucket: 'zero-ads-gallery.firebasestorage.app',
    iosBundleId: 'com.example.galleryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN7UtCYEJFpON3emyrG_PYdS6D1R7-2IU',
    appId: '1:138769918502:web:8cd4eb223d9556f0fed4e7',
    messagingSenderId: '138769918502',
    projectId: 'zero-ads-gallery',
    authDomain: 'zero-ads-gallery.firebaseapp.com',
    storageBucket: 'zero-ads-gallery.firebasestorage.app',
  );

}